config/routes.rb
Rails.application.routes.draw do
 
  resources :companies
  resources :users
  resources :reports
  resources :visits
  resources :departments

  root to: 'application#index'

  get 'visits/index' => 'visits#all'

  
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :department
  belongs_to :user
  belongs_to :company

  attr_reader :data

  def self.mesAtual(data)
    date = Date.today

    @visits = []
  	@visits.each do |v|
  		if ((v.saida.month == data.month) && (v.saida.year == data.year))
       	@visits << v
  		end
  	end
  	@visits
  end

  def state
    done? ? 'done' : 'yet'
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: [:show, :edit, :update, :destroy]
  
  
  # GET /visits
  # GET /visits.json
  def index
    @visits = Visit.all
    @departments = Department.all
    @users = User.all
    @companies = Company.all
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, notice: 'Visit was successfully created.' }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to @visit, notice: 'Visit was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit.destroy
    respond_to do |format|
      format.html { redirect_to visits_url, notice: 'Visit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visit_params
      params.require(:visit).permit(:name, :rg, :cpf, :department_id, :user_id, :entrada, :saida, :company_id)
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: 'Nome do visitante' %>
    <div class="form-inline">
      <div class="form-group">
        <%= f.text_field :rg, class: 'form-control ', placeholder: 'Registro Geral' %>
        <%= f.text_field :cpf, class: 'form-control ', placeholder: 'CPF' %>
      </div>
    </div>
    <br />
    <div class="form-inline">
      <div class="form-group">
       <label> Selecione o departamento: </label>
        <%= f.collection_select(:department_id, Department.all,:id, :nome,{}, {class: 'form-control'}) %>
        </div>
      </div>
         <br />
    <div class="form-inline">
      <label> Selecione o servidor: </label>
      <%= f.collection_select(:user_id, User.all, :id, :name, {},{class: 'form-control', placeholder: 'Funcionário'}) %>
    </div>
    <br />
    <div class="form-inline">
      <%= f.label "Entrada", class: 'control-label' %>
      <br />
      <%= f.datetime_select(:entrada, {:order => [:day,:month, :year]},{class: 'form-control glyphicon glyphicon-calendar aria-hidden="true"'}) %>
    </div>
    <div class="form-inline">
      <%= f.label "Saida    ", class: 'control-label' %>
      <br />
      <%= f.datetime_select(:saida,{:order => [:day,:month, :year]}, class: 'form-control glyphicon glyphicon-calendar aria-hidden="true"', placeholder: 'Empresa') %>
    </div>
    <br />
    <div class="form-inline">
      <label>Selecione a empresa</label>
      <%= f.collection_select(:company_id, Company.all, :id, :nome, {},{class: 'form-control', placeholder: 'Empresa'}) %>
    </div>
   
  
  <div class="actions">
    <br />
    <%= f.submit "Cadastrar visita", class: 'btn btn-primary'%>
  </div>
  <br />
<% end %>

app/views/visits/edit.html.erb
<h3>Editar Visita</h3>

<%= render 'form' %>

<%= link_to 'Visualizar', @visit %> |
<%= link_to 'Voltar', visits_path %>

app/views/visits/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Visitantes</h3>
<div class="table-responsive">

<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Rg</th>
      <th>Cpf</th>
      <th>Departmento</th>
      <th>Funcionario</th>
      <th>Entrada</th>
      <th>Saída</th>
      <th>Empresa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visits.each do |visit| %>
      <tr>
        <td><%= visit.name %></td>
        <td><%= visit.rg %></td>
        <td><%= visit.cpf %></td>
        <td><%= visit.department.nome %></td>
        <td><%= visit.user.name %></td>
        <td><%= visit.entrada.strftime("%d/%m/%Y - %H:%M") %></td>
        <td><%= visit.saida.strftime("%d/%m/%Y - %H:%M") %></td>
        <td><%= visit.company.nome %></td>
        <td><%= link_to '', visit, class: 'glyphicon glyphicon-search aria-hidden="true"' %></td>
        <td><%= link_to '', edit_visit_path(visit), class: 'glyphicon glyphicon-pencil aria-hidden="true" ' %></td>
        <td><%= link_to '', visit, method: :delete, data: { confirm: 'tem certeza que gostaria de apagar esta visita?' }, class: 'glyphicon glyphicon-remove aria-hidden="true"' %></td>
      </tr>

      
    <% end %>
  </tbody>
</table>

<br>
</div>
<%= link_to 'Cadastrar visita', new_visit_path %>
<br />

app/views/visits/new.html.erb
<h3>Cadastro de visita</h3>

<%= render 'form' %>

<%= link_to 'Voltar', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive">
<p>
  <strong>Name:</strong>
  <%= @visit.name %>
</p>

<p>
  <strong>Rg:</strong>
  <%= @visit.rg %>
</p>

<p>
  <strong>Cpf:</strong>
  <%= @visit.cpf %>
</p>

<p>
  <strong>Department:</strong>
  <%= @visit.department %>
</p>

<p>
  <strong>User:</strong>
  <%= @visit.user %>
</p>

<p>
  <strong>Entrada:</strong>
  <%= @visit.entrada %>
</p>

<p>
  <strong>Saida:</strong>
  <%= @visit.saida %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @visit.company %>
</p>
</div>

<%= link_to 'Editar', edit_visit_path(@visit) %> |
<%= link_to 'Voltar', visits_path %>