config/routes.rb
Rails.application.routes.draw do
 
  resources :companies
  resources :users
  resources :reports
  resources :visits
  resources :departments

  root to: 'application#index'

  get 'visits/index' => 'visits#all'

  
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:nome, :telefone, :cnpj, :endereco, :numero, :complemento, :cep, :bairro, :cidade, :estado)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
   <%= f.text_field :nome , class: 'form-control ', placeholder: 'Empresa'%>
    <br />  
     <%= f.text_field :cnpj, class: 'form-control ', placeholder: 'CNPJ' %>
     <br />
    <%= f.text_field :endereco, class: 'form-control ', placeholder: 'Endereço' %>
    <br />
    <div class="form-inline">      
      <%= f.text_field :numero, class: 'form-control ', placeholder: 'Número' %>
      <%= f.text_field :complemento, class: 'form-control ', placeholder: 'Complemento' %>
      <%= f.text_field :bairro, class: 'form-control', placeholder: 'Bairro' %>
     </div>
     <br />
    <div class="form-inline">
      <%= f.text_field :cep, class: 'form-control', placeholder: 'CEP' %>
    </div>
    <br />
    <div class="form-inline">
      <%= f.select(:estado, option_estados_for_select,{}, {class: 'form-control ', placeholder: 'Estado'}) %>
      <%= f.text_field :cidade, class: 'form-control ', placeholder: 'Cidade' %>
    </div>
 
   
  </div>
  
  <div class="actions">
    <%= f.submit "Cadastrar empresa" , class: 'btn btn-primary'%>
  </div>
</div>
<% end %>

app/views/companies/edit.html.erb
<h3>Editar empresa </h3>

<%= render 'form' , class: 'form-horizontal'%>

<%= link_to 'Listar empresas', @company %> |
<%= link_to 'Voltar', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Empresas</h3>

<div class="table-responsive">

<table class="table">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Telefone</th>
      <th>Cnpj</th>
      <th>Endereco</th>
      <th>Numero</th>
      <th>Complemento</th>
      <th>Cep</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.nome %></td>
        <td><%= company.telefone %></td>
        <td><%= company.cnpj %></td>
        <td><%= company.endereco %></td>
        <td><%= company.numero %></td>
        <td><%= company.complemento %></td>
        <td><%= company.cep %></td>
        <td><%= company.bairro %></td>
        <td><%= company.cidade %></td>
        <td><%= company.estado %></td>
        <td><%= link_to '', company, class: 'glyphicon glyphicon-search aria-hidden="true"' %></td>
        <td><%= link_to '', edit_company_path(company),class: 'glyphicon glyphicon-pencil aria-hidden="true" ' %></td>
        <td><%= link_to '', company, method: :delete, data: { confirm: 'Tem certeza que gostaria de exluir os dados da empresa?' },class: 'glyphicon glyphicon-remove aria-hidden="true"' %></td>



      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'Cadastrar nova empresa', new_company_path %>
<br />

app/views/companies/new.html.erb
<h3>Cadastro de empresa</h3>

<%= render 'form' %>

<br />

<%= link_to 'Voltar', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<div class="table-responsive">

<p>
  <strong>Nome:</strong>
  <%= @company.nome %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @company.telefone %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @company.cnpj %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @company.endereco %>
</p>

<p>
  <strong>Número:</strong>
  <%= @company.numero %>
</p>

<p>
  <strong>Complemento:</strong>
  <%= @company.complemento %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @company.cep %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @company.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @company.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @company.estado %>
</p>

</div>

<%= link_to 'Editar', edit_company_path(@company) %> |
<%= link_to 'Voltar', companies_path %>