config/routes.rb
Rails.application.routes.draw do
 
  resources :companies
  resources :users
  resources :reports
  resources :visits
  resources :departments

  root to: 'application#index'

  get 'visits/index' => 'visits#all'

  
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :company
  belongs_to :user
  belongs_to :visit
  belongs_to :department



  def state
    done? ? 'done' : 'yet'
  end
  
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]
  
  
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
    data = Date.today
    @visits = Visit.where("extract(month from saida)= ? and extract(year from saida) = ?",data.month, data.year)
    #@visits = Visit.all
    respond_to do |format|
      format.html
      format.pdf { render_reportVisits(@visits) }
    end
    
  end

  

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:empresa_id, :user_id, :visit_id, :department_id)
    end

    def render_reportVisits(visits)
      report = ThinReports::Report.new layout: File.join(Rails.root, 'app', 'views', 'reports' ,  'relatorioVisitas.tlf')

      visits.each do |visit|
        report.list.add_row do |row|
          row.values nomeVisit: visit.name, 
                     cpfVisit: visit.cpf,
                     inicioVisit: visit.entrada,
                     fimVisit: visit.saida,
                     departamentoVisit: visit.department.nome,
                     funcVisit: visit.user.name
          #row.item(:nomeVisit).style(:color, 'red') unless visit.done?
        end
      end

      send_data report.generate, filename: 'relatorioVisitas.pdf', 
                                 type: 'application/pdf', 
                                 disposition: 'attachment'
    end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :empresa_id %><br>
    <%= f.text_field :empresa_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :visit_id %><br>
    <%= f.text_field :visit_id %>
  </div>
  <div class="field">
    <%= f.label :department_id %><br>
    <%= f.text_field :department_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_mesAtual.html.erb
<div class="table-responsive"> 
	<table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Cpf</th>
        <th>Departamento</th>
        <th>Data entrada</th>
        <th>Data saida</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @visits.each do |visit| %>
        <tr>
          <td><%= visit.name %></td>
          <td><%= visit.cpf %></td>
          <td><%= visit.department.nome %></td>
          <td><%= visit.entrada %></td>
          <td><%= visit.saida %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/reports/_porData.html.erb
<div class="table-responsive"> 
	Teste 2

</div>

app/views/reports/_porDepart.html.erb
<div class="table-responsive"> 
	Teste 3

</div>

app/views/reports/_porFunc.html.erb
<div class="table-responsive"> 
	Teste 4

</div>

app/views/reports/edit.html.erb
<h3>Editing Report</h3>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Relatórios</h3>

  <%= link_to "Mês atual", {controller: "reports", action: "index", filtro: "teste"} %>
  <ul class="nav nav-tabs" role="tablist">
    <li id="mesAtual" class="active"><%= link_to "Mês atual", "/reports" %></a></li>
    <li id="porData"><a href="#" data-toggle="tab">Por Datas</a></li>
    <li id="porDepart"><a href="#" data-toggle="tab">Por Departamento</a></li>
    <li id="porFunc"><a href="#" data-toggle="tab">Por Funcionário</a></li>
  </ul>

<div class="tab-content">
  <div class="tab-pane fade in active" id="mesAtual">
   <%= render partial: "mesAtual" %>
   
  </div>

  <div class="tab-pane fade" id="porData">
    <%= render partial: "porData" %>
  </div>

  <div class="tab-pane fade" id="porDepart">
    <%= render partial: "porDepart" %>
  </div>

  <div class="tab-pane fade" id="porFunc">
    <%= render partial: "porFunc" %>
  </div>

</div>













<!--<table class="table">
  <thead>
    <tr>
      <th><button class="btn btn-primary">  </button></th>
      <th><button class="btn btn-primary">  </button></th>
      <th><button class="btn btn-primary">  </button></th>
      <th><button class="btn btn-primary"> Por Funcionário </button></th>
      <th colspan="3"></th>
    </tr>
  </thead>
</table>
</div>
<br> -->

<!--%= link_to 'New Report', new_report_path %> -->
<%= link_to 'Imprimir relatório', reports_path(format: 'pdf') %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Empresa:</strong>
  <%= @report.empresa %>
</p>

<p>
  <strong>User:</strong>
  <%= @report.user %>
</p>

<p>
  <strong>Visit:</strong>
  <%= @report.visit %>
</p>

<p>
  <strong>Department:</strong>
  <%= @report.department %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>